name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    env:
      CC:   gcc
      MAKE: make
      LDD:  ldd

    steps:
    - uses: actions/checkout@v4

#    - name: Install neofetch
#      run: sudo apt install -y neofetch

    # ここから共通 ----------
    - name: version - date, uname, gcc, make
      run: |
        date
        uname -a
        echo "----------"
        $CC --version
        $MAKE --version
        mkdir current-build-ubuntu

    - name: run rls debug
      run: |
        $MAKE clean debug
        ./rls -always

    - name: run rls md5
      run: |
        $MAKE clean md5
        ./rls -always -fmogcdw5NkPle -alr
        cp ./rls ./current-build-ubuntu/rls

    - name: make, ldd
      run: |
        $MAKE clean wrapper count
        echo "----------"
        $MAKE clean
        $MAKE
        echo $LDD ./rls
        $LDD ./rls

    - name: rls version, help
      run: |
        ./rls --version
        echo "----------"
        ./rls --help

    - name: run rls
      run: |
        ./rls -alr -TB\[ -TE\]
        echo "----------"
        ./rls -alr -always
        echo "----------"
        ./rls -TB\[ -TE\]
        echo "----------"
        ./rls -always

    - name: Create ZIP
      run: |
        cp ./README_english.md ./current-build-ubuntu
        zip -r current-build-ubuntu.zip current-build-ubuntu

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: current-build-ubuntu
        path: current-build-ubuntu.zip


  ## --------------------------------------------------
  ## md5 がダメそうなので一旦コンパイルだけ
  build_macos:
    runs-on: macos-latest
    env:
      CC:   /usr/local/bin/gcc
      MAKE: gmake
      LDD:  otool -L
    steps:
    - uses: actions/checkout@v4

    ## インストールしないと clang が使用される
    - name: install gcc
      uses: Dup4/actions-setup-gcc@v1
#      with:
#        version: latest

    - name: Install gmake, openssl
      run: |
        brew install make
#        brew install openssl

    # ここから共通 ----------
    - name: version - date, uname, cc, make
      run: |
        date
        uname -a
        echo "----------"
        $CC --version
        $MAKE --version
        mkdir current-build-macos

#    - name: run rls debug
#      run: |
#        $MAKE clean debug
#        ./rls -always

    # ここがダメ
    - name: run rls md5
      run: |
        export OPENSSL_DIR=$(brew --prefix openssl@3)
        gcc -I$OPENSSL_DIR/include -L$OPENSSL_DIR/lib -DMD5 rls.c -lssl -lcrypto -o rls
        ./rls -always -fmogcdw5NkPle -alr
        cp ./rls ./current-build-macos/rls

    - name: make, ldd
      run: |
        $MAKE clean wrapper count
        echo "----------"
        $MAKE clean
        $MAKE
        echo $LDD ./rls
        $LDD ./rls

    - name: rls version, help
      run: |
        ./rls --version
        echo "----------"
        ./rls --help

    - name: run rls
      run: |
        ./rls -alr -TB\[ -TE\]
        echo "----------"
        ./rls -alr -always
        echo "----------"
        ./rls -TB\[ -TE\]
        echo "----------"
        ./rls -always

    - name: Create ZIP
      run: |
        cp ./README_english.md ./current-build-macos
        zip -r current-build-macos.zip current-build-macos

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: current-build-macos
        path: current-build-macos.zip
